from agent.models import AgentState

# ── Severity config ────────────────────────────────────────────────────────────

SEVERITY_EMOJI = {
    "high":   "🔴",
    "medium": "🟡",
    "low":    "🔵",
}

SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}

# ── Node ───────────────────────────────────────────────────────────────────────

def format_comment(state: AgentState) -> dict:
    findings = sorted(state["findings"], key=lambda f: SEVERITY_ORDER[f["severity"]])
    meta = state["pr_metadata"]

    high   = [f for f in findings if f["severity"] == "high"]
    medium = [f for f in findings if f["severity"] == "medium"]
    low    = [f for f in findings if f["severity"] == "low"]

    sections = [_header(meta, findings)]

    if not findings:
        sections.append("✅ No security issues found in the changed lines.")
    else:
        if high:
            sections.append(_section("High severity", "high", high))
        if medium:
            sections.append(_section("Medium severity", "medium", medium))
        if low:
            sections.append(_section("Low severity", "low", low))

    sections.append(_footer())

    return {"comment_body": "\n\n".join(sections)}

# ── Helpers ────────────────────────────────────────────────────────────────────

def _header(meta: dict, findings: list) -> str:
    total = len(findings)
    high  = sum(1 for f in findings if f["severity"] == "high")
    status = "⚠️ Issues found" if findings else "✅ Clean"

    return f"""## 🔍 Automated Security Review
**PR:** {meta['title']}
**Status:** {status} — {total} finding(s) ({high} high severity)
**Reviewed files:** {meta['changed_files']} changed (+{meta['additions']} -{meta['deletions']} lines)

---"""


def _section(title: str, severity: str, findings: list) -> str:
    emoji = SEVERITY_EMOJI[severity]
    lines = [f"### {emoji} {title}"]

    for f in findings:
        confidence_pct = int(f["confidence"] * 100)
        lines.append(f"""**`{f["file"]}`** — line {f["line"]}
> {f["description"]}
*Confidence: {confidence_pct}%*""")

    return "\n\n".join(lines)


def _footer() -> str:
    return """---
*Generated by PR Security Reviewer · Only changed lines were analyzed · [How this works](https://github.com)*"""