from agent.models.state import AgentState

SEVERITY_EMOJI = {
    "high":     "🔴",
    "medium":   "🟡",
    "low":      "🔵",
    "critical": "🚨",
}

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}

def format_comment(state: AgentState) -> dict:
    findings     = sorted(state.get("findings", []),    key=lambda f: SEVERITY_ORDER.get(f["severity"], 99))
    orphan_cves  = state.get("orphan_cves", [])
    meta         = state["pr_metadata"]

    sections = [_header(meta, findings, orphan_cves)]

    if not findings and not orphan_cves:
        sections.append("✅ No security issues found in the changed lines.")
    else:
        if findings:
            sections.append(_findings_section(findings))
        if orphan_cves:
            sections.append(_orphan_cves_section(orphan_cves))

    sections.append(_footer())

    return {"comment_body": "\n\n".join(sections)}


# ── Helpers ────────────────────────────────────────────────────────────────────

def _header(meta: dict, findings: list, orphan_cves: list) -> str:
    total    = len(findings)
    critical = sum(1 for f in findings if f["severity"] == "critical")
    high     = sum(1 for f in findings if f["severity"] == "high")
    status   = "⚠️ Issues found" if findings or orphan_cves else "✅ Clean"

    return f"""## 🔍 Automated Security Review
**PR:** {meta['title']}
**Status:** {status} — {total} finding(s) ({critical} critical, {high} high severity)
**Reviewed files:** {meta['changed_files']} changed (+{meta['additions']} -{meta['deletions']} lines)

---"""


def _findings_section(findings: list) -> str:
    lines = ["### Code findings"]

    for f in findings:
        emoji      = SEVERITY_EMOJI.get(f["severity"], "⚪")
        confidence = int(f["confidence"] * 100)

        block = f"""{emoji} **[{f['severity'].upper()}]** `{f['file']}` — line {f['line']}
> {f['description']}
*Confidence: {confidence}%*"""

        # OWASP classification
        if f.get("owasp_code"):
            block += f"\n**OWASP:** {f['owasp_code']} — {f['owasp_name']}"
            if f.get("owasp_rationale"):
                block += f" · *{f['owasp_rationale']}*"

        # Related CVEs
        if f.get("related_cves"):
            cve_lines = []
            for cve in f["related_cves"]:
                aliases  = ", ".join(cve["aliases"]) if cve["aliases"] else cve["id"]
                severity = f"[{cve['severity'].upper()}] " if cve.get("severity") else ""
                cve_lines.append(f"  - {severity}`{aliases}` — {cve['summary']}")
            block += "\n**Related CVEs:**\n" + "\n".join(cve_lines)

        lines.append(block)

    return "\n\n".join(lines)


def _orphan_cves_section(orphan_cves: list) -> str:
    lines = ["### ⚠️ Vulnerable dependencies detected"]
    lines.append("*These packages were added or modified in this PR and have known CVEs:*")

    for cve in orphan_cves:
        aliases  = ", ".join(cve["aliases"]) if cve["aliases"] else cve["id"]
        severity = SEVERITY_EMOJI.get(cve.get("severity", ""), "⚪")
        lines.append(
            f"{severity} **`{cve['package']}`** {cve['version']} — "
            f"`{aliases}`\n> {cve['summary']}"
        )

    return "\n\n".join(lines)


def _footer() -> str:
    return """---
*Generated by PR Security Reviewer · Only changed lines were analyzed · OWASP Top 10 (2021) · CVE data via [OSV](https://osv.dev)*"""